### PR TITLE
Build `If-check`

### PR DESCRIPTION
**Pull request by manushak**
### Types of changes

- [x] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### A description of the changes proposed in the Pull Request

-  Add functionality to check if the provided manifest outputs are correct
- There are 2 cases to test:
- When you provide manifest file path: `npm run if-check — -m ./manifests/outputs/manifest.yaml`. If the outputs are the same as the generated manifest file, it should print `Files match!` or  
`Files do not match!
tree.children.child.outputs.0.cpu/energy
source: 0.08333333333333333
target: 0.1`
- When you provide a directory path where placed manifests files are: `npm run if-check — -d ./manifests/output/`. It should print every file name with the execution result
-

### CODE REVIEW

**Review by jmcook1186 — APPROVED** [review]
sgtm, but could you remove the `<` and `>` characters wrapping tyhe filename in the response message?

i.e. like this:
```
if-check could not verify teads-curve.yml
```

not this
```
if-check could not verify <teads-curve.yml>
```

**Review by narekhovhannisyan — APPROVED** [review]

**Comment by MariamKhalatova** [comment]
When folder doesn't contain any yamls, only checking message is shown.
Expected Behavior: Folder is empty, or similar message.

Screenshot 2024-06-28 at 1 47 33 AM

**Comment by MariamKhalatova** [comment]
When running with prefix weird error appears.

Screenshot 2024-06-28 at 1 56 00 AM

**Comment by jmcook1186** [comment]
lgtm - thanks :o)

**Pull request merged**
