### PR TITLE
implement `If-diff` script

### PR DESCRIPTION
**Pull request by narekhovhannisyan**
### Types of changes

- [ ] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### A description of the changes proposed in the Pull Request

- Implement `if-diff` script.
-

### CODE REVIEW

**Review by jmcook1186 — CHANGES_REQUESTED** [review]
`if-diff` is returning a failure response based on `execution.command` which is supposed to be a ignored field.
Please ignore all information in `execution` EXCEPT `status` and `error`.

**Comment by narekhovhannisyan** [comment]
@jmcook1186 it will be covered with #706

**Review by jmcook1186 — APPROVED** [review]
sgtm - I checked out locally and verified that:
- two identical files return success response
- two non-matching files returned failure response and expected diff report
- piping from `ie` to `if-diff` worked as expected

**Review by jmcook1186 — CHANGES_REQUESTED** [review]
Must fix https://github.com/Green-Software-Foundation/if/issues/734
and https://github.com/Green-Software-Foundation/if/issues/733 from QA review
before this can be merged

**Review by MariamKhalatova — CHANGES_REQUESTED** [review]
@narekhovhannisyan In case of using wildcard , the '*' is accepted as a value, and an error is received. 
``` 
Files do not match!
tree.children.child-0.outputs[0].cpu/utilization
source: *
target: 20
```

**Review by MariamKhalatova — CHANGES_REQUESTED** [review]
@narekhovhannisyan When the quantity of array members doesn't match in source and target files, then the following error is received. 
**Expected result:** Should show the first missing array member

```
Files do not match!
tree.children.child-0.outputs
source: [object Object]
target: [object Object],[object Object],[object Object]
```

**Comment by narekhovhannisyan** [comment]
fixes #733
fixes #734

**Review by MariamKhalatova — APPROVED** [review]

**Pull request merged**
