### PR TITLE
Update If-check to support CI/CD

### PR DESCRIPTION
**Pull request by manushak**
### Types of changes

- [x] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### A description of the changes proposed in the Pull Request

- Add error summary log when checking directory files
- add process.exit(1) at the end of the catch

### CODE REVIEW

**Review by jmcook1186 — APPROVED** [review]
sgtm!

**Comment by narekhovhannisyan** [comment]
@manushak @jmcook1186 it works but we have a bug and there is suggestion for improvement.

Right now we are getting the following:

```
Checking...

copy.yaml
if-check could not verify copy.yaml. The re-executed file does not match the original.

Files do not match!
tree.children.child-1.outputs.0.mock
source: exists
target: missing

generics.yaml
if-check successfully verified generics.yaml

instance-metadata.yaml
if-check successfully verified instance-metadata.yaml
copy.yaml
Files do not match!


Summary of all failing files:
2 of 3 files are passed.

tree.children.child-1.outputs.0.mock
source: exists
target: missing
```

Which means after summary we are getting logs

**Comment by narekhovhannisyan** [comment]
As an improvement to UI we can modify messages like this:

```
Checking...

Executing `copy.yaml`
✖ if-check could not verify copy.yaml. The re-executed file does not match the original.
Files do not match!
tree.children.child-1.outputs.0.mock
source: exists
target: missing

Executing `generics.yaml`
✔ if-check successfully verified `generics.yaml`

Executing `instance-metadata.yaml`
✔ if-check successfully verified `instance-metadata.yaml`

Executing `copy.yaml`
✖ Files do not match!
tree.children.child-1.outputs.0.mock
source: exists
target: missing

Tests summary:
2 of 3 files are passed.
```

**Review by narekhovhannisyan — CHANGES_REQUESTED** [review]
Please check comments above

**Comment by jmcook1186** [comment]
ok I like the proposed updates but also liked that @manushak 's version separated out the individual emitted logs from the summary of failures.  think we need some kind of break between the emitted messages and the "summary" - even if it is just a line break and `summary` title, e.g.

```
Checking...

Executing `copy.yaml`
✖ if-check could not verify copy.yaml. The re-executed file does not match the original.
Files do not match!
tree.children.child-1.outputs.0.mock
source: exists
target: missing

Executing `generics.yaml`
✔ if-check successfully verified `generics.yaml`

Executing `instance-metadata.yaml`
✔ if-check successfully verified `instance-metadata.yaml`

---
if-check verification failures:
---

Executing `copy.yaml`
✖ Files do not match!
tree.children.child-1.outputs.0.mock
source: exists
target: missing

---
Tests summary:
2 of 3 files are passed.
```

**Comment by narekhovhannisyan** [comment]
@jmcook1186 it doesn't look like intentional solution since title is before summary, the rest is after.

**Review by narekhovhannisyan — APPROVED** [review]

**Pull request merged**
