### PR TITLE
CSV Lookup builtin plugin

### PR DESCRIPTION
**Pull request by narekhovhannisyan**
### Types of changes

- [ ] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### A description of the changes proposed in the Pull Request

- This pull request adds CSV Lookup plugin to if framework's builtins.
- Covers the introduced changes with documentation and unit tests.
- Adds appropriate manifests samples.

### CODE REVIEW

**Review by jmcook1186 — APPROVED** [review]
Added some test manifests and tidied up the readme, but otherwise this seems good. I have played around with it quite a bit and checked that it does what we expected. I haven't found any unexpected behaviour. Happy to pass to qa.

**Review by MariamKhalatova — CHANGES_REQUESTED** [review]
@narekhovhannisyan When the value of `output` doesn't match with existing key, in the result output section a new param with the value of `output` value appears . 
Expected result: Throw appropriate error
Screenshot 2024-06-04 at 1 54 31 AM

**Comment by MariamKhalatova** [comment]
@narekhovhannisyan When a value of output field is a two dimensional array and arrays contain only one field name, the output is broken. 
Screenshot 2024-06-04 at 12 04 26 PM

**Comment by MariamKhalatova** [comment]
@narekhovhannisyan When plugin output is `"*"`, outputs contain duplicates from query.
Screenshot 2024-06-04 at 9 56 09 PM

**Comment by MariamKhalatova** [comment]
@narekhovhannisyan please also check, all exported values are string.

**Comment by narekhovhannisyan** [comment]
@MariamKhalatova I've pushed fixes, please check

**Review by MariamKhalatova — APPROVED** [review]

**Pull request merged**
