### PR TITLE
Bug report template

### PR DESCRIPTION
**Pull request by MariamKhalatova**
### Types of changes

- [ ] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### A description of the changes proposed in the Pull Request

- 
-

### CODE REVIEW

**Review by jawache — CHANGES_REQUESTED** [review]
@MariamKhalatova I don't believe this matches the fields listed in the acceptance criteria of the ticket.

Also can we use a normal markdown template, I find these formatted templates are hard to maintain and harder to use when you are adding lots of text, screenshots etc...

**Comment by jawache** [comment]
I personally find them harder to use as you can't just edit in another file and submit, I often write out long issues in a blank markdown file in my computer as it takes me sometime to collect all the information and I'm scared I'll accidentally close the browser window and lose all my info. 

When I've crafted the content correctly I then paste into the issue. It's also harder to maintain we've used them in other places and a 1 min task ends up taking a few hours as people have to learn a new format and some simple things like adding text is much harder to get right 

If people don't submit a proper bug report we reject and ask them to submit properly instead.

**Review by jmcook1186 — CHANGES_REQUESTED** [review]
Hi team @jawache @MariamKhalatova @narekhovhannisyan 

Appreciate the effort in making the bug report template more user friendly - it does look nice. But I agree with @jawache that this doesn't meet the requirements of the ticket because the fields are different, and it's better to keep a very simple markdown template as its more maintainable and flexible - I also like to draft things in a markdown editor and copy/paste.

Please can you update the fields so that they match what's specified in the ticket and make it a markdown template?

**Comment by MariamKhalatova** [comment]
@jawache @jmcook1186 No problem, will modify the template to markdown format, with the fields specified in the ticket.

**Comment by MariamKhalatova** [comment]
Updates are pushed on https://github.com/Green-Software-Foundation/if/pull/654 . Closing this one, as it's not actual anymore.

**Pull request closed without merging**
