### PR TITLE
Zero tolerant plugins

### PR DESCRIPTION
**Pull request by narekhovhannisyan**
### Types of changes

- [x] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### A description of the changes proposed in the Pull Request

- 
-

### CODE REVIEW

**Comment by jmcook1186** [comment]
looks good @narekhovhannisyan , except `zero-minus-one` yields `1` instead of `-1` when i run the manifest from the issue ticket.

**Comment by narekhovhannisyan** [comment]
@jmcook1186 it's because of typo in your manifest
please use this fixed one

```yaml
name: generics
description: a pipeline that does arbitrary calculations using our generic arithmetic builtins
tags:
initialize:
  plugins:
    "sum-zero-and-one":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - some-value
          - zero-value
        output-parameter: one-plus-zero
    "sum-zero-and-zero":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - zero-value
          - zero-value
        output-parameter: zero-plus-zero
    "subtract-one-and-zero":
      path: "builtin"
      method: Subtract
      global-config:
        input-parameters:
          - some-value
          - zero-value
        output-parameter: one-minus-zero
    "subtract-zero-and-zero":
      path: "builtin"
      method: Sum
      global-config:
        input-parameters:
          - zero-value
          - zero-value
        output-parameter: zero-minus-zero
    "subtract-zero-and-one":
      path: "builtin"
      method: Subtract
      global-config:
        input-parameters:
          - zero-value
          - some-value
        output-parameter: zero-minus-one
    "coefficient-one-times-zero":
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: zero-value
        coefficient: 1
        output-parameter: zero-times-one-coefficient
    "coefficient-zero-times-one":
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: some-value
        coefficient: 0
        output-parameter: one-times-zero-coefficient
    "coefficient-zero-times-zero":
      path: "builtin"
      method: Coefficient
      global-config:
        input-parameter: zero-value
        coefficient: 0
        output-parameter: zero-times-zero-coefficient
    "multiply-one-times-zero":
      path: "builtin"
      method: Multiply
      global-config:
        input-parameters: ["some-value", "zero-value"]
        output-parameter: "one-times-zero"
    "multiply-zero-times-one":
      path: "builtin"
      method: Multiply
      global-config:
        input-parameters: ["zero-value", "zero-value"]
        output-parameter: "zero-times-one"
    exponent-one-to-zero:
      method: Exponent
      path: 'builtin'
      global-config:
        input-parameter: 'some-value'
        exponent: 0
        output-parameter: 'one-raised-to-zero-power'
    exponent-zero-to-zero:
      method: Exponent
      path: 'builtin'
      global-config:
        input-parameter: 'zero-value'
        exponent: 0
        output-parameter: 'zero-raised-to-zero-power'
    exponent-zero-to-one:
      method: Exponent
      path: 'builtin'
      global-config:
        input-parameter: 'zero-value'
        exponent: 1
        output-parameter: 'zero-raised-to-first-power'
    "sci":
      path: "builtin"
      method: Sci
      global-config:
        functional-unit: "zero-value"
tree:
  children:
    child-1:
      pipeline:
        - sum-zero-and-one
        - sum-zero-and-zero
        - subtract-one-and-zero
        - subtract-zero-and-zero
        - subtract-zero-and-one
        - coefficient-one-times-zero
        - coefficient-zero-times-one
        - coefficient-zero-times-zero
        - multiply-one-times-zero
        - multiply-zero-times-one
        - exponent-one-to-zero
        - exponent-zero-to-one
        - exponent-zero-to-zero
        # - sci
      config:
      defaults:
      inputs:
        - timestamp: "2023-12-12T00:00:00.000Z"
          duration: 1
          some-value: 1
          zero-value: 0
```

**Comment by jmcook1186** [comment]
Got it - thanks

**Review by jmcook1186 — APPROVED** [review]
lgtm!

**Review by manushak — APPROVED** [review]

**Pull request merged**
