### PR TITLE
Prettify the regroup code

### PR DESCRIPTION
**Pull request by narekhovhannisyan**
### Types of changes

- [x] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### A description of the changes proposed in the Pull Request

- 
-

### CODE REVIEW

**Review by manushak — CHANGES_REQUESTED** [review]
@narekhovhannisyan these changes do not solve the problem. When executing the regroup manifest, it still regroups again

**Comment by narekhovhannisyan** [comment]
@manushak we decided to leave that for now, since it requires a lot of changes. This one is just refactored version of initial code.

**Review by manushak — APPROVED** [review]

**Review by jmcook1186 — APPROVED** [review]

**Comment by Eakinter99** [comment]
> @narekhovhannisyan these changes do not solve the problem. When executing the regroup manifest, it still regroups again

**Comment by narekhovhannisyan** [comment]
Hi @Eakinter99, thanks for the feedback. You can check my message in the thread above.

**Pull request merged**
