### PR TITLE
Add `explain` feature

### PR DESCRIPTION
**Pull request by manushak**
### Types of changes

- [x] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### A description of the changes proposed in the Pull Request

- add `explain` and `explainer` properties in the manifest
- to test add `explainer: true` in the manifest file and execute it, the necessary data will be provided in the execute section.

### CODE REVIEW

**Comment by narekhovhannisyan** [comment]
Screenshot 2024-07-19 at 17 15 44
@manushak It will be better to have some default messages for the cases where information is not available.

**Comment by jmcook1186** [comment]
Agree with @narekhovhannisyan - maybe we can use:
`x not available - please set x in the initialize block for y plugin`

**Comment by manushak** [comment]
> Agree with @narekhovhannisyan - maybe we can use: `x not available - please set x in the initialize block for y plugin` @manushak

@jmcook1186 here `undefined` means that the user hasn't set `inputs` and `outputs` in the `parameter-metadata`.
Since it is not possible to add inputs and outputs to the manifest if they have undefined values (as undefined properties are skipped from the manifest), I've added the string undefined. I see two solutions for this: either add empty [] or skip those properties from the manifest if they have undefined values. What do you think?

**Comment by jmcook1186** [comment]
In that case, maybe it's better just to leave them as `undefined` and just make it clear in the documentation that the remedy is to add parameter metadata in the `initialize` block.

**Review by jmcook1186 — APPROVED** [review]
lgtm, pending update to aggregation method as discussed in #916

**Review by narekhovhannisyan — APPROVED** [review]

**Pull request merged**
