### PR TITLE
Eco-CI - Estimating the cost of CI pipelines

### PR DESCRIPTION
**Pull request by ArneTR**
### Types of changes

- [ ] Enhancement (project structure, spelling, grammar, formatting)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

### A description of the changes proposed in the Pull Request
This pull requests is a bit out of the ordinary ... I guess :)

I work for an open source company called Green Coding Solutions in Germany and we started with the mission to increase awareness and actionability around digital CO2 emissions.

We have recently created an open source CI/CD plugin called Eco-CI. 
- [Project page](https://www.green-coding.io/projects/eco-ci/)
- [Github Page](https://github.com/green-coding-solutions/eco-ci-energy-estimation)

It integrates into the Github Actions pipeline and estimates the energy and CO2 consumption of the pipeline by utilizing a Machine Learning model trained on real server energy data from [SPECpower](https://www.spec.org/power_ssj2008/results/)

The tool creates awareness of the energy cost and carbon emissions of CI/CD pipelines and empoweres developers to create action for more sustainability.
It can separate steps of the pipeline and create detailed drill-downs which step has increased / decreased in carbon emissions and provider great insights into pipeline performance in general.

In this PR I have made a sample integration into the `.github/workflows/nodejs-ci.yml` pipeline.

The PR is also for the Open Source WG meeting with @seanmcilroy29 that we are invited in on Thursday to have some example discuss.

I hope this PR and the information that Eco-CI provides is interesting for you and I am super interested in your feedback on  it. 

## Changelog

- Added Eco-CI into the `.github/workflows/nodejs-ci.yml` pipeline
- Activated the `send-data: true` flag. This will send data to be used as historical data view on https://metrics.green-coding.io/ci-index.html . If this is not desired it must be set to false.

## Demo

- An example of where we have run it before making the PR in the forked repository
  - https://github.com/green-coding-solutions/if/actions/runs/9170239374
- See an example how the  Pull-Request view looks like: 
  - https://github.com/green-coding-solutions/nmf-app/pull/1
- See the data over time for many runs:
  -  https://metrics.green-coding.io/ci.html?repo=green-coding-solutions%2Fif&branch=eco-ci&workflow=99010494

@ribalba @MichelleGruene

### CODE REVIEW

**Comment by jmcook1186** [comment]
Hi @ArneTR thanks for this PR and sorry for the slow response. 
In principle I'm happy to bring this in as I'm intrigued to see how your system works, but going to assign to @narekhovhannisyan to review first to check it won't break anything related to our CI/CD.
(Also, we won't be able to merge unless you resolve the DCO requirement by adding a DCO commit).

**Comment by ArneTR** [comment]
Hey @jmcook1186 ,

- I force pushed the PR and squashed all unsigned commits into one DCO conforming signed one. Sorry about that
- Thanks for the kind words and that you like it. We also presented our tool to the Standards WG and it is currently [there also under review for a SCI use case](https://github.com/Green-Software-Foundation/sci-guide/issues/61). Just some background info ...
- Maybe to lighten the work on validating for your pipeline: We ran the pipeline in our forked repo and there it showed no issues: https://github.com/green-coding-solutions/if/actions also all steps are using `continue-on-error` to be double safe.

**Comment by jmcook1186** [comment]
@narekhovhannisyan quick reminder to review and approve if you are happy

**Comment by jmcook1186** [comment]
Hi @ArneTR - curious whether the energy/carbon data you predict using EcoCI is exposed via an API? If so, we would love to have a system where your app is part of our CI/CD but we can also query the estimates using an IF plugin to give a neat way to include our CI/CD in estimates of our project's overall impact.

**Review by jmcook1186 — APPROVED** [review]

**Comment by ArneTR** [comment]
> Hi @ArneTR - curious whether the energy/carbon data you predict using EcoCI is exposed via an API? If so, we would love to have a system where your app is part of our CI/CD but we can also query the estimates using an IF plugin to give a neat way to include our CI/CD in estimates of our project's overall impact.

There are two ways:
- You can use the underlying model - [Cloud Energy](https://github.com/green-coding-solutions/cloud-energy) which can effectivley be used anywhere where Python runs. I also had a discussion with @jawache about the idea of bringing it to IF but we didn't have the time to catch up on this

- The alternative, if you are already sending the data to our free API endpoint (by setting the send-data: true switch as done in this PR) you will be able to use our API to retrieve the data.
Since the data shows here: https://metrics.green-coding.io/ci-index.html the corresponding API to query the results is here: https://api.green-coding.io/docs . The endpoint would be `GET /v1/ci/measurements`

**Review by narekhovhannisyan — APPROVED** [review]

**Comment by ArneTR** [comment]
Thanks for the merge.

For the sake of completeness:
- Data is either in the PR itself or visible here: https://github.com/Green-Software-Foundation/if/actions/runs/9859922421
- Aggregated data (for main branch in this case) is here: https://metrics.green-coding.io/ci.html?repo=Green-Software-Foundation/if&branch=main&workflow=66389738

Super happy for any feedback as soon as you have aquired some data!

**Comment by jmcook1186** [comment]
Thanks @ArneTR , this is very cool. I've looked at the dashboard data and it's very useful - much kudos to your team!

 I'm really keen to have an IF plugin that hits the API so that the environmental costs of the CI/CD can be included in a broader LCA for the project. I haven't been able to make a successful request yet, even just using curl, so I must be making some basic syntax error, but I haven't been able to sit and dig in properly yet. If I keep having problems maybe I could connect with one of your team for some support?

**Comment by ArneTR** [comment]
This is the full API endpoint: https://api.green-coding.io/v1/ci/measurements?repo=Green-Software-Foundation/if&branch=main&workflow=66389738&start_date=2024-06-11&end_date=2024-07-11

You can even open it in the browser

**Comment by ArneTR** [comment]
please note that the "branch" and "workflow" parameter changes for every branch and PR that is targeted

**Comment by jmcook1186** [comment]
got it - thanks a lot!

**Pull request merged**
